// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// infrared_send //
// ------------- //

#define infrared_send_wrap_target 0
#define infrared_send_wrap 5
#define infrared_send_pio_version 0

static const uint16_t infrared_send_program_instructions[] = {
            //     .wrap_target
    0x6020, //  0: out    x, 32           side 0
    0xa142, //  1: nop                    side 0 [1]
    0xb742, //  2: nop                    side 1 [7]
    0x0f41, //  3: jmp    x--, 1          side 0 [15]
    0x6020, //  4: out    x, 32           side 0
    0x0045, //  5: jmp    x--, 5          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program infrared_send_program = {
    .instructions = infrared_send_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = infrared_send_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config infrared_send_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + infrared_send_wrap_target, offset + infrared_send_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ---------------- //
// infrared_receive //
// ---------------- //

#define infrared_receive_wrap_target 0
#define infrared_receive_wrap 24
#define infrared_receive_pio_version 0

static const uint16_t infrared_receive_program_instructions[] = {
            //     .wrap_target
    0xe020, //  0: set    x, 0
    0x80a0, //  1: pull   block
    0xa047, //  2: mov    y, osr
    0x2020, //  3: wait   0 pin, 0
    0xa029, //  4: mov    x, ~x
    0x0046, //  5: jmp    x--, 6
    0xa029, //  6: mov    x, ~x
    0x00a9, //  7: jmp    x != y, 9
    0x0016, //  8: jmp    22
    0x00cb, //  9: jmp    pin, 11
    0x0404, // 10: jmp    4                      [4]
    0x4020, // 11: in     x, 32
    0xe020, // 12: set    x, 0
    0xa029, // 13: mov    x, ~x
    0x004f, // 14: jmp    x--, 15
    0xa029, // 15: mov    x, ~x
    0x00b2, // 16: jmp    x != y, 18
    0x0016, // 17: jmp    22
    0x05cd, // 18: jmp    pin, 13                [5]
    0x4020, // 19: in     x, 32
    0xe020, // 20: set    x, 0
    0x0004, // 21: jmp    4
    0xe020, // 22: set    x, 0
    0x4020, // 23: in     x, 32
    0x0018, // 24: jmp    24
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program infrared_receive_program = {
    .instructions = infrared_receive_program_instructions,
    .length = 25,
    .origin = -1,
    .pio_version = infrared_receive_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config infrared_receive_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + infrared_receive_wrap_target, offset + infrared_receive_wrap);
    return c;
}
#endif

